databases:
  - name: jordidb-01
    ipAllowlist: []
    plan: free

services:
  - type: web
    name: rails
    plan: free
    env: ruby
    buildCommand: "./backend/bin/render-build.sh"
    startCommand: bundle exec rails s
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: jordidb-01
          property: connectionString

  - type: redis
    name: redis
    ipAllowlist: []
    plan: free
    maxmemoryPolicy: noeviction
