databases:
  - name: jordidb-01
    # databaseName: jordidb_01
    # user: jordi
    ipAllowlist: []
    plan: free

services:
  - type: web
    name: rails
    runtime: ruby
    plan: free
    buildCommand: "./backend/bin/render-build.sh"
    # preDeployCommand: "bundle exec rails db:migrate" # preDeployCommand only available on paid instance types
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: jordidb-01
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default

  -type: redis
    name: redis
    plan: free
    ipAllowlist: []
Do